FROM node:22-alpine

WORKDIR /app

ARG JWT_SECRET
ARG JWT_EXPIRES
ARG DATABASE_URL
ARG API_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG OPENWEATHER_API_KEY

ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRES=$JWT_EXPIRES
ENV DATABASE_URL=$DATABASE_URL
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV OPENWEATHER_API_KEY=$OPENWEATHER_API_KEY

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]